package remedy

import (
	"encoding/json"
	"io"
	"net/http"
	"net/http/httptest"
	"testing"
	"time"

	"github.com/google/go-github/v92/github"
	"github.com/stretchr/testify/require"

	"github.com/giantswarm/marge/internal/pr"
)

func TestCloseClosesThePR(t *testing.T) {
	var body map[string]any
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		raw, _ := io.ReadAll(r.Body)
		_ = json.Unmarshal(raw, &body)
		_, _ = w.Write([]byte(`{"number": 1, "state": "closed"}`))
	}))
	defer server.Close()

	req := botRequest(apiClient(t, server))
	req.Pull.State = new("open")

	out, err := Default().Apply(t.Context(), Close, req, nil)

	require.NoError(t, err)
	require.True(t, out.Applied)
	require.Equal(t, "closed", body["state"])
}

// An Align files PR is regenerated every cycle, so closing it only makes the
// bot open it again.
func TestCloseRefusesAnAlignFilesPR(t *testing.T) {
	req := botRequest(nil)
	req.Kind = pr.KindAlignFiles
	req.Pull.User = &github.User{Login: new("giantswarm-align-files[bot]")}

	out, err := Default().Apply(t.Context(), Close, req, nil)

	require.NoError(t, err)
	require.False(t, out.Applied)
	require.Contains(t, out.Refused, "regenerated, not closed")
}

func TestCloseRefusesAnAlreadyClosedPR(t *testing.T) {
	req := botRequest(nil)
	req.Pull.State = new("closed")

	out, err := Default().Apply(t.Context(), Close, req, nil)

	require.NoError(t, err)
	require.Equal(t, "the PR is already closed", out.Refused)
}

func TestMarkWaitKeepsTheClassification(t *testing.T) {
	out, err := Default().Apply(t.Context(), MarkWait, botRequest(nil), nil)

	require.NoError(t, err)
	require.True(t, out.Applied)
	require.True(t, out.KeepClassification)
}

func TestDispatchAlignWorkflowNamesTheRepository(t *testing.T) {
	var path string
	var body map[string]any
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		path = r.URL.Path
		raw, _ := io.ReadAll(r.Body)
		_ = json.Unmarshal(raw, &body)
		w.WriteHeader(http.StatusNoContent)
	}))
	defer server.Close()

	out, err := Default().Apply(t.Context(), DispatchAlignWorkflow, botRequest(apiClient(t, server)), nil)

	require.NoError(t, err)
	require.True(t, out.Applied)
	require.True(t, out.KeepClassification)
	require.Equal(t, "/repos/giantswarm/github/actions/workflows/align-files.yaml/dispatches", path)
	require.Equal(t, "main", body["ref"])
	require.Equal(t, map[string]any{"repository": "marge"}, body["inputs"])
}

func TestDispatchCVEWorkflowRunsOnTheBaseBranch(t *testing.T) {
	var path string
	var body map[string]any
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		path = r.URL.Path
		raw, _ := io.ReadAll(r.Body)
		_ = json.Unmarshal(raw, &body)
		w.WriteHeader(http.StatusNoContent)
	}))
	defer server.Close()

	out, err := Default().Apply(t.Context(), DispatchCVEWorkflow, botRequest(apiClient(t, server)), nil)

	require.NoError(t, err)
	require.True(t, out.Applied)
	require.True(t, out.KeepClassification)
	require.Equal(t, "/repos/giantswarm/marge/actions/workflows/zz_generated.fix_vulnerabilities.yaml/dispatches", path)
	require.Equal(t, "main", body["ref"])
	require.Equal(t, map[string]any{"branch": "main"}, body["inputs"])
}

// TestDispatchCVEWorkflowRefusesAHandEdit demonstrates the refusal the
// never-edit list exists for: an action that names a generated path among
// the files it would write never reaches its API call.
func TestDispatchCVEWorkflowRefusesAHandEdit(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(http.ResponseWriter, *http.Request) {
		t.Error("the workflow was dispatched although the request names a generated file")
	}))
	defer server.Close()

	req := botRequest(apiClient(t, server))
	req.Writes = []string{cveWorkflow}

	out, err := Default().Apply(t.Context(), DispatchCVEWorkflow, req, nil)

	require.NoError(t, err)
	require.False(t, out.Applied)
	require.Contains(t, out.Refused, "is generated by giantswarm/github")
}

const protection = `{"strict": true, "contexts": ["go-build", "go-test", "package and push alfred-app chart"]}`

// driftRequest is a PR whose head has finished reporting, which is what
// tells a context nobody posts from a job that has not started yet.
func driftRequest(client *github.Client, stale ...string) *Request {
	req := botRequest(client)
	req.Now = time.Now()
	req.Reported = 2
	req.ChecksSettledAt = req.Now.Add(-2 * protectionSettleDelay)
	req.Required.Missing = stale
	req.MissingContexts = stale
	return req
}

func protectionServer(t *testing.T, after string) (*httptest.Server, *[]byte) {
	t.Helper()
	var written []byte
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Method == http.MethodPatch {
			written, _ = io.ReadAll(r.Body)
			_, _ = w.Write([]byte(after))
			return
		}
		_, _ = w.Write([]byte(protection))
	}))
	return server, &written
}

func TestFixProtectionContextDropsTheStaleContexts(t *testing.T) {
	const after = `{"strict": true, "contexts": ["go-build", "go-test"]}`
	server, written := protectionServer(t, after)
	defer server.Close()

	req := driftRequest(apiClient(t, server), "package and push alfred-app chart")

	out, err := Default().Apply(t.Context(), FixProtectionContext, req, nil)

	require.NoError(t, err)
	require.True(t, out.Applied)
	require.Contains(t, out.Detail, "package and push alfred-app chart")

	var sent map[string]any
	require.NoError(t, json.Unmarshal(*written, &sent))
	require.Equal(t, []any{"go-build", "go-test"}, sent["contexts"])
	require.NotContains(t, sent, "strict", "the write never changes strict")
}

// A branch left with no required check is weaker than the one the migration
// left behind, so that decision stays with a person.
func TestFixProtectionContextRefusesToEmptyTheProtection(t *testing.T) {
	server, _ := protectionServer(t, protection)
	defer server.Close()

	req := driftRequest(apiClient(t, server), "go-build", "go-test", "package and push alfred-app chart")

	out, err := Default().Apply(t.Context(), FixProtectionContext, req, nil)

	require.NoError(t, err)
	require.False(t, out.Applied)
	require.Contains(t, out.Refused, "would leave main with none")
}

func TestFixProtectionContextRefusesWithNothingMissing(t *testing.T) {
	out, err := Default().Apply(t.Context(), FixProtectionContext, driftRequest(nil), nil)

	require.NoError(t, err)
	require.Equal(t, "every required context reported", out.Refused)
}

// A context the head has not reported yet is not one no job posts any more.
// Without the settle guard a queued workflow reads as drift, and the remedy
// for that is a branch-protection write nobody asked for.
func TestFixProtectionContextWaitsForTheHeadToSettle(t *testing.T) {
	server, written := protectionServer(t, protection)
	defer server.Close()

	req := driftRequest(apiClient(t, server), "package and push alfred-app chart")
	req.ChecksSettledAt = req.Now.Add(-time.Minute)

	out, err := Default().Apply(t.Context(), FixProtectionContext, req, nil)

	require.NoError(t, err)
	require.False(t, out.Applied)
	require.Contains(t, out.Refused, "may still report for the first time")
	require.Empty(t, *written, "no protection is written while the head may still report")
}

// The rule names the contexts it diagnosed, and the action drops those. A
// context missing for another reason stays required.
func TestFixProtectionContextDropsOnlyWhatTheRuleNamed(t *testing.T) {
	const after = `{"strict": true, "contexts": ["go-build", "go-test"]}`
	server, written := protectionServer(t, after)
	defer server.Close()

	req := driftRequest(apiClient(t, server), "package and push alfred-app chart")
	req.Required.Missing = []string{"package and push alfred-app chart", "go-test"}

	out, err := Default().Apply(t.Context(), FixProtectionContext, req, nil)

	require.NoError(t, err)
	require.True(t, out.Applied)

	var sent map[string]any
	require.NoError(t, json.Unmarshal(*written, &sent))
	require.Contains(t, sent["contexts"], "go-test", "a context the rule did not name stays required")
}

// A rule that named no context leaves the action nothing to diagnose, so it
// never falls back to dropping whatever is missing.
func TestFixProtectionContextRefusesWithoutARuleSelection(t *testing.T) {
	server, written := protectionServer(t, protection)
	defer server.Close()

	req := driftRequest(apiClient(t, server))
	req.Required.Missing = []string{"package and push alfred-app chart"}

	out, err := Default().Apply(t.Context(), FixProtectionContext, req, nil)

	require.NoError(t, err)
	require.False(t, out.Applied)
	require.Contains(t, out.Refused, "named no missing context")
	require.Empty(t, *written)
}

// The write is read back. A context still required afterwards stops the
// sweep for that repository rather than reporting a fix that did not happen.
func TestFixProtectionContextReadsTheWriteBack(t *testing.T) {
	server, _ := protectionServer(t, protection)
	defer server.Close()

	req := driftRequest(apiClient(t, server), "package and push alfred-app chart")

	out, err := Default().Apply(t.Context(), FixProtectionContext, req, nil)

	require.Error(t, err)
	require.True(t, out.StopRepository)
}
