package remedy

import (
	"testing"
	"time"

	"github.com/google/go-github/v92/github"
	"github.com/stretchr/testify/require"

	"github.com/giantswarm/marge/internal/pr"
)

func botPull(login string) *github.PullRequest {
	return &github.PullRequest{User: &github.User{Login: new(login)}}
}

func TestTrustedAuthor(t *testing.T) {
	require.Empty(t, TrustedAuthor.Refuse(&Request{Pull: botPull("renovate[bot]")}))
	require.Empty(t, TrustedAuthor.Refuse(&Request{Pull: botPull("heraldbot[bot]")}))
	require.Contains(t, TrustedAuthor.Refuse(&Request{Pull: botPull("QuentinBisson")}), "not a trusted bot")
}

func TestNoSecurityFailure(t *testing.T) {
	require.Empty(t, NoSecurityFailure.Refuse(&Request{}))
	require.Equal(t, "security check failed: govulncheck", NoSecurityFailure.Refuse(&Request{SecurityFailure: "govulncheck"}))
}

func TestRequiredChecksGreen(t *testing.T) {
	tests := []struct {
		name     string
		required Required
		want     string
	}{
		{
			name:     "every required context green",
			required: Required{Green: []string{"go-build"}},
		},
		{
			name:     "a failed context refuses",
			required: Required{Failed: []string{"go-build"}},
			want:     "required checks failed: go-build",
		},
		{
			name:     "a pending context waits",
			required: Required{Green: []string{"go-build"}, Pending: []string{"go-test"}},
			want:     "required checks pending: go-test",
		},
		{
			name:     "a context nobody reported waits",
			required: Required{Green: []string{"go-build"}, Missing: []string{"pre-commit"}},
			want:     "required checks not reported: pre-commit",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			require.Equal(t, tt.want, RequiredChecksGreen.Refuse(&Request{Required: tt.required}))
		})
	}
}

func TestLogMatched(t *testing.T) {
	require.Empty(t, LogMatched.Refuse(&Request{LogMatched: true}))
	require.Contains(t, LogMatched.Refuse(&Request{}), "check name alone")
}

func TestOncePerChange(t *testing.T) {
	guard := OncePerChange(CircleCIRetry)
	require.Empty(t, guard.Refuse(&Request{}))
	require.Empty(t, guard.Refuse(&Request{AppliedThisChange: map[Name]bool{RerunFailed: true}}))
	require.Equal(t, "circleci-retry already applied to this change",
		guard.Refuse(&Request{AppliedThisChange: map[Name]bool{CircleCIRetry: true}}))
}

func TestNoGeneratedEdit(t *testing.T) {
	tests := []struct {
		name   string
		writes []string
		want   string
	}{
		{
			name:   "repository owned files are writable",
			writes: []string{"Makefile.custom.mk", "helm/marge/Chart.yaml", ".ats/main.yaml", ".abs/main.yaml", "go.sum"},
		},
		{
			name:   "renovate-custom.json5 is repository owned",
			writes: []string{"renovate-custom.json5"},
		},
		{
			name:   "a zz_ file at the repository root is refused",
			writes: []string{"zz_generated.app-platform.values.yaml"},
			want:   "generated by giantswarm/github",
		},
		{
			name:   "a zz_ workflow is refused at any depth",
			writes: []string{".github/workflows/zz_generated.pre-commit.yaml"},
			want:   "generated by giantswarm/github",
		},
		{
			name:   "the devctl renovate config is refused",
			writes: []string{"renovate.json5"},
			want:   "generated by devctl",
		},
		{
			name:   "the align-managed pre-commit config is refused",
			writes: []string{"./.pre-commit-config.yaml"},
			want:   "generated by devctl",
		},
		{
			name:   "the generated CircleCI workflows are refused",
			writes: []string{"go.mod", ".circleci/workflows.yml"},
			want:   "generated by devctl",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := NoGeneratedEdit.Refuse(&Request{Writes: tt.writes})
			if tt.want == "" {
				require.Empty(t, got)
				return
			}
			require.Contains(t, got, tt.want)
		})
	}
}

func TestTrustedAuthorCoversEveryKind(t *testing.T) {
	for _, login := range pr.TrustedLogins() {
		require.Empty(t, TrustedAuthor.Refuse(&Request{Pull: botPull(login)}), login)
	}
}

// A context nobody reported is drift only once the head has finished
// reporting. A workflow that has not created its check run yet is the same
// observation, and rewriting a branch protection over it is a write nobody
// asked for.
func TestChecksSettled(t *testing.T) {
	now := time.Date(2026, 9, 15, 12, 0, 0, 0, time.UTC)
	settled := func(quiet time.Duration) *Request {
		return &Request{Now: now, Reported: 3, ChecksSettledAt: now.Add(-quiet)}
	}

	tests := []struct {
		name    string
		request *Request
		want    string
	}{
		{
			name:    "the head has reported nothing",
			request: &Request{Now: now},
			want:    "reported no check yet",
		},
		{
			name:    "a required context is pending",
			request: &Request{Now: now, Reported: 3, Required: Required{Pending: []string{"build"}}},
			want:    "required checks pending: build",
		},
		{
			name:    "a check is still running",
			request: &Request{Now: now, Reported: 3, ChecksPending: true},
			want:    "has not finished",
		},
		{
			name:    "nothing carries a completion time",
			request: &Request{Now: now, Reported: 3},
			want:    "no completion time",
		},
		{
			name:    "the newest report is recent",
			request: settled(5 * time.Minute),
			want:    "may still report for the first time",
		},
		{
			name:    "the head has been quiet",
			request: settled(protectionSettleDelay + time.Minute),
			want:    "",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			reason := ChecksSettled.Refuse(tt.request)
			if tt.want == "" {
				require.Empty(t, reason)
				return
			}
			require.Contains(t, reason, tt.want)
		})
	}
}

// A zero Now is a request the engine did not fill, and the guard fails
// closed on it rather than reading every past report as settled.
func TestChecksSettledRefusesWithoutATime(t *testing.T) {
	req := &Request{Reported: 3, ChecksSettledAt: time.Date(2020, 1, 1, 0, 0, 0, 0, time.UTC)}

	require.Contains(t, ChecksSettled.Refuse(req), "may still report for the first time")
}

// Every guard of every action carries a name. The name is what a report
// prints, so an action whose guard set is invisible is one nobody reviews.
func TestEveryGuardIsNamed(t *testing.T) {
	registry := Default()

	for _, name := range registry.Names() {
		t.Run(string(name), func(t *testing.T) {
			action, ok := registry.Lookup(name)
			require.True(t, ok)
			require.NotEmpty(t, action.Guards(), "an action with no guard refuses nothing")
			for _, guard := range action.Guards() {
				require.NotEmpty(t, guard.Name)
			}
			require.Equal(t, len(action.Guards()), len(registry.GuardNames(name)))
		})
	}
}

func TestKnownCommand(t *testing.T) {
	tests := []struct {
		name     string
		commands []string
		want     string
	}{
		{
			name:     "the app suite the gate names",
			commands: []string{"/run app-test-suites-single PROVIDER=capa"},
		},
		{
			name:     "the cluster suite",
			commands: []string{"/run cluster-test-suites"},
		},
		{
			name:     "one command per provider",
			commands: []string{"/run app-test-suites-single PROVIDER=capa", "/run app-test-suites-single PROVIDER=capz"},
		},
		{
			name:     "several arguments",
			commands: []string{"/run app-test-suites-single PROVIDER=capa TARGET_SUITES=basic,defaultapp"},
		},
		{
			name: "no command captured",
			want: "captured no command",
		},
		{
			name:     "a pipeline the sweep does not start",
			commands: []string{"/run delete-everything"},
			want:     `pipeline "delete-everything" is not one the sweep starts`,
		},
		{
			name:     "a command with a shell tail",
			commands: []string{"/run cluster-test-suites; rm -rf /"},
			want:     "is not a /run command",
		},
		{
			name:     "prose around the command",
			commands: []string{"please /run cluster-test-suites"},
			want:     "is not a /run command",
		},
		{
			name:     "one good command and one bad one",
			commands: []string{"/run cluster-test-suites", "/merge"},
			want:     "is not a /run command",
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			refusal := KnownCommand.Refuse(&Request{Commands: tc.commands})
			if tc.want == "" {
				require.Empty(t, refusal)
				return
			}
			require.Contains(t, refusal, tc.want)
		})
	}
}

func TestOnlyGateWaiting(t *testing.T) {
	gate := "Heimdall - PR Gatekeeper"

	require.Empty(t, OnlyGateWaiting.Refuse(&Request{
		Check:    gate,
		Required: Required{Green: []string{"go-build"}, Pending: []string{gate}},
	}))

	require.Contains(t, OnlyGateWaiting.Refuse(&Request{
		Check:    gate,
		Required: Required{Failed: []string{"ci/circleci: push-to-app-catalog"}},
	}), "required checks failed")

	require.Contains(t, OnlyGateWaiting.Refuse(&Request{
		Check:    gate,
		Required: Required{Pending: []string{gate, "check-values-schema / validate"}},
	}), "pending besides")

	require.Contains(t, OnlyGateWaiting.Refuse(&Request{
		Check:    gate,
		Required: Required{Pending: []string{gate}},
		Failing:  []string{"semantic-pull-request / Validate PR title"},
	}), "checks failed")

	require.Contains(t, OnlyGateWaiting.Refuse(&Request{
		Check:    gate,
		Required: Required{Missing: []string{"Check sync.sh was called"}},
	}), "not reported")
}
