package remedy

import (
	"testing"

	"github.com/google/go-github/v92/github"
	"github.com/stretchr/testify/require"

	"github.com/giantswarm/marge/internal/pr"
)

func botPull(login string) *github.PullRequest {
	return &github.PullRequest{User: &github.User{Login: new(login)}}
}

func TestTrustedAuthor(t *testing.T) {
	require.Empty(t, TrustedAuthor(&Request{Pull: botPull("renovate[bot]")}))
	require.Empty(t, TrustedAuthor(&Request{Pull: botPull("heraldbot[bot]")}))
	require.Contains(t, TrustedAuthor(&Request{Pull: botPull("QuentinBisson")}), "not a trusted bot")
}

func TestNoSecurityFailure(t *testing.T) {
	require.Empty(t, NoSecurityFailure(&Request{}))
	require.Equal(t, "security check failed: govulncheck", NoSecurityFailure(&Request{SecurityFailure: "govulncheck"}))
}

func TestRequiredChecksGreen(t *testing.T) {
	tests := []struct {
		name     string
		required Required
		want     string
	}{
		{
			name:     "every required context green",
			required: Required{Green: []string{"go-build"}},
		},
		{
			name:     "a failed context refuses",
			required: Required{Failed: []string{"go-build"}},
			want:     "required checks failed: go-build",
		},
		{
			name:     "a pending context waits",
			required: Required{Green: []string{"go-build"}, Pending: []string{"go-test"}},
			want:     "required checks pending: go-test",
		},
		{
			name:     "a context nobody reported waits",
			required: Required{Green: []string{"go-build"}, Missing: []string{"pre-commit"}},
			want:     "required checks not reported: pre-commit",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			require.Equal(t, tt.want, RequiredChecksGreen(&Request{Required: tt.required}))
		})
	}
}

func TestLogMatched(t *testing.T) {
	require.Empty(t, LogMatched(&Request{LogMatched: true}))
	require.Contains(t, LogMatched(&Request{}), "check name alone")
}

func TestOncePerChange(t *testing.T) {
	guard := OncePerChange(CircleCIRetry)
	require.Empty(t, guard(&Request{}))
	require.Empty(t, guard(&Request{AppliedThisChange: map[Name]bool{RerunFailed: true}}))
	require.Equal(t, "circleci-retry already applied to this change",
		guard(&Request{AppliedThisChange: map[Name]bool{CircleCIRetry: true}}))
}

func TestNoGeneratedEdit(t *testing.T) {
	tests := []struct {
		name   string
		writes []string
		want   string
	}{
		{
			name:   "repository owned files are writable",
			writes: []string{"Makefile.custom.mk", "helm/marge/Chart.yaml", ".ats/main.yaml", ".abs/main.yaml", "go.sum"},
		},
		{
			name:   "renovate-custom.json5 is repository owned",
			writes: []string{"renovate-custom.json5"},
		},
		{
			name:   "a zz_ file at the repository root is refused",
			writes: []string{"zz_generated.app-platform.values.yaml"},
			want:   "generated by giantswarm/github",
		},
		{
			name:   "a zz_ workflow is refused at any depth",
			writes: []string{".github/workflows/zz_generated.pre-commit.yaml"},
			want:   "generated by giantswarm/github",
		},
		{
			name:   "the devctl renovate config is refused",
			writes: []string{"renovate.json5"},
			want:   "generated by devctl",
		},
		{
			name:   "the align-managed pre-commit config is refused",
			writes: []string{"./.pre-commit-config.yaml"},
			want:   "generated by devctl",
		},
		{
			name:   "the generated CircleCI workflows are refused",
			writes: []string{"go.mod", ".circleci/workflows.yml"},
			want:   "generated by devctl",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := NoGeneratedEdit(&Request{Writes: tt.writes})
			if tt.want == "" {
				require.Empty(t, got)
				return
			}
			require.Contains(t, got, tt.want)
		})
	}
}

func TestTrustedAuthorCoversEveryKind(t *testing.T) {
	for _, login := range pr.TrustedLogins() {
		require.Empty(t, TrustedAuthor(&Request{Pull: botPull(login)}), login)
	}
}
