{{- range $entry := (include "marge.schedules" . | fromYamlArray) }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "marge.cronServiceAccountName" (dict "context" $ "component" $entry.name) }}
  labels:
    {{- include "marge.labels" $ | nindent 4 }}
    {{- include "marge.scheduleLabels" (dict "entry" $entry) | nindent 4 }}
  {{- with $.Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}
