{{- if include "marge.writesTokenSecret" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "marge.tokenSecretName" . }}
  labels:
    {{- include "marge.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if and .Values.marge.github.token (not .Values.marge.github.existingSecret) }}
  github-token: {{ .Values.marge.github.token | quote }}
  {{- end }}
  {{- if and .Values.marge.circleci.token (not .Values.marge.circleci.existingSecret) }}
  circleci-token: {{ .Values.marge.circleci.token | quote }}
  {{- end }}
{{- end }}
